<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page-setting[
<!ELEMENT page-setting (css-files?,jscript-files?,pages?)>
<!ELEMENT css-files (css-file+)>
<!ELEMENT jscript-files (jscript-file+)>
<!ELEMENT pages (page+)>
  <!ELEMENT page (regulartransmission?,enterkey-orders?)>
  <!ELEMENT enterkey-orders (enterkey-order*)>
  <!ATTLIST css-file path CDATA #REQUIRED>
  <!ATTLIST jscript-file path CDATA #REQUIRED>
  <!ATTLIST page path CDATA #REQUIRED resource-key CDATA #REQUIRED>
  <!ATTLIST enterkey-order order NMTOKEN #REQUIRED control-id CDATA #REQUIRED>
  <!ATTLIST regulartransmission time CDATA #REQUIRED>

]>
<page-setting>
  <css-files>
    <css-file path="/css/common.css" />
    <css-file path="/css/listcell.css" />
    <css-file path="/css/tool.css" />
    <css-file path="/css/user.css" />
  </css-files>
  <jscript-files>
    <jscript-file path="/jscript/common.js" />
    <jscript-file path="/jscript/user.js" />
  </jscript-files>
  <pages>
    <!-- eManager START -->
    <page path="/login/ScreenLogin" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/login/Login" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/Progress" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/Dispatch" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/Error" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/login/LoginSuccess" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/login/ChangePassword" resource-key="TLE-T0035">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/menu/MainMenuA" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/menu/MainMenuB" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/menu/SubMenu" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/login/AutoLogin" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/ScreenLock" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/menu/MainMenu" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_R_MenuId" />
        <enterkey-order order="2" control-id="txt_MenuResourceKey" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/listbox/MainMenuList" resource-key="TLE-T0002">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/menu/listbox/ResourceList" resource-key="TLE-T0003">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/menu/MainMenuOrder" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/menu/FunctionOrder" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_MainMenu" />
        <enterkey-order order="2" control-id="pul_SubMenu" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/Role" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RoleId" />
        <enterkey-order order="2" control-id="txt_RoleName" />
        <enterkey-order order="3" control-id="rdo_FailedLoginAttempts1" />
        <enterkey-order order="4" control-id="txt_FailedLoginAttempts" />
        <enterkey-order order="5" control-id="rdo_PWDChangeInterval1" />
        <enterkey-order order="6" control-id="txt_PasswordChangeInterval" />
        <enterkey-order order="7" control-id="rdo_TargetCommon" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/listbox/RoleList" resource-key="TLE-T0041">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/user/RoleMap" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_Role" />
        <enterkey-order order="2" control-id="chk_All" />
        <enterkey-order order="3" control-id="lst_RoleMap" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/User" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_UserId" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_Password_Re" />
        <enterkey-order order="4" control-id="rdo_PwdChangeInterval" />
        <enterkey-order order="5" control-id="txt_PwdChangeInterval" />
        <enterkey-order order="6" control-id="txt_RoleId" />
        <enterkey-order order="7" control-id="rdo_SameUserLoginMax" />
        <enterkey-order order="8" control-id="txt_SameUserLoginMax" />
        <enterkey-order order="9" control-id="rdo_UserLock_OFF" />
        <enterkey-order order="10" control-id="rdo_FailedLoginRestricted" />
        <enterkey-order order="11" control-id="txt_FailedLoginAttempts" />
        <enterkey-order order="12" control-id="txt_UserName" />
        <enterkey-order order="13" control-id="txt_Belonging" />
        <enterkey-order order="14" control-id="txt_Note" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/listbox/UserList" resource-key="TLE-T0015">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/user/Terminal" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_TerminalNumber" />
        <enterkey-order order="2" control-id="txt_TerminalName" />
        <enterkey-order order="3" control-id="rdo_SpecifiesIPAddress" />
        <enterkey-order order="4" control-id="txt_IpAddress" />
        <enterkey-order order="5" control-id="txt_HostName" />
        <enterkey-order order="6" control-id="txt_RoleId" />
        <enterkey-order order="7" control-id="txt_PrinterName" />
        <enterkey-order order="8" control-id="rdo_AutoLoginON" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/listbox/TerminalList" resource-key="TLE-T0017">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/system/FinalCheck" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/system/BackUp" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_FileBrows" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/system/Restore" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_FileBrows" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/CsvLogExport" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="chk_AuthLog" />
        <enterkey-order order="2" control-id="chk_MainteLog" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/SearchAuthLog1" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="chk_IncludeLog" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/listbox/CsvLogFileList" resource-key="TLE-T0037">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/SearchAuthLog2" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LogDateRetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_LogTimeRetrievalBeginn" />
        <enterkey-order order="3" control-id="txt_LogDateRetrievalEnd" />
        <enterkey-order order="4" control-id="txt_LogTimeRetrievalEnd" />
        <enterkey-order order="5" control-id="pul_LogClass" />
        <enterkey-order order="6" control-id="txt_UserId" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/SearchMainteLog1" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="chk_IncludeLog" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/SearchMainteLog2" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LogDateRetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_LogTimeRetrievalBeginn" />
        <enterkey-order order="3" control-id="txt_LogDateRetrievalEnd" />
        <enterkey-order order="4" control-id="txt_LogTimeRetrievalEnd" />
        <enterkey-order order="5" control-id="pul_LogClass" />
        <enterkey-order order="6" control-id="txt_UserId" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/UserRecovery" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_UserId" />
        <enterkey-order order="2" control-id="txt_Password" />
        <enterkey-order order="3" control-id="txt_PasswordAgain" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/listbox/TerminalChangeList" resource-key="TLE-T0040">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="lst_TerminalChange" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/user/listbox/TerminalUserList" resource-key="LBL-T0096">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="lst_UserChange" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/SubMenu" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_MenuId" />
        <enterkey-order order="2" control-id="txt_FunctionResourceKey" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/SubMenuOrder" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_MainMenu" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/listbox/SubMenuList" resource-key="TLE-T0005">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/setting/system/AuthenticationSystem1" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LoginMax" />
        <enterkey-order order="2" control-id="rdo_SameLoginUser_ON" />
        <enterkey-order order="3" control-id="rdo_AutoLogin_ON" />
        <enterkey-order order="4" control-id="rdo_ScreenLogInCheck_ON" />
        <enterkey-order order="5" control-id="txt_SessionTimeoutTime" />
        <enterkey-order order="6" control-id="rdo_TerminalChange_ON" />
        <enterkey-order order="7" control-id="rdo_TerminalUserCheck_ON" />
        <enterkey-order order="8" control-id="rdo_TerminalCheck_ON" />
        <enterkey-order order="9" control-id="rdo_IPRangeCheck_ON" />
        <enterkey-order order="10" control-id="txt_IPRange_Min" />
        <enterkey-order order="11" control-id="txt_IPRange_Max" />
        <enterkey-order order="12" control-id="rdo_FailedLoginScreenLock_ON" />
        <enterkey-order order="13" control-id="txt_FailedLoginScreenLockCount" />
        <enterkey-order order="14" control-id="txt_FailedLoginScreenLockTime" />
        <enterkey-order order="15" control-id="rdo_FailedLoginUserLock_ON" />
        <enterkey-order order="16" control-id="rdo_FailedLoginAttempts" />
        <enterkey-order order="17" control-id="txt_FailedLoginAttempts" />
        <enterkey-order order="18" control-id="rdo_DummyPassWord_ON" />
        <enterkey-order order="19" control-id="txt_PasswordLogCheckTime" />
        <enterkey-order order="20" control-id="txt_PasswordMinLength" />
        <enterkey-order order="21" control-id="rdo_PassWordSaftyCheck_ON" />
        <enterkey-order order="22" control-id="rdo_PasswordExpire_ON" />
        <enterkey-order order="23" control-id="rdo_PwdChangeInterval" />
        <enterkey-order order="24" control-id="txt_PwdChangeInterval" />
        <enterkey-order order="25" control-id="txt_PasswordExpireAlertDays" />
        <enterkey-order order="26" control-id="rdo_Part11Log_ON" />
        <enterkey-order order="27" control-id="rdo_AccessLog_ON" />
        <enterkey-order order="28" control-id="rdo_MasterLog_ON" />
        <enterkey-order order="29" control-id="rdo_StockLog_ON" />
        <enterkey-order order="30" control-id="rdo_OperationLog_ON" />
        <enterkey-order order="31" control-id="txt_DBLogHoldDays" />
        <enterkey-order order="32" control-id="txt_CsvLogHoldDays" />
        <enterkey-order order="33" control-id="txt_HDLogHoldYears" />
        <enterkey-order order="34" control-id="rdo_AuthenticationLog_ON" />
        <enterkey-order order="35" control-id="rdo_UserMaintenanceLog_ON" />
        <enterkey-order order="36" control-id="rdo_SameUserBlock_restricted" />
        <enterkey-order order="37" control-id="txt_SameUserCreateBlockPeriod" />
        <enterkey-order order="38" control-id="rdo_LargeIcon" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/system/AuthenticationSystem2" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_FailedLoginScreenLockTime" />
        <enterkey-order order="2" control-id="txt_SessionTimeoutTime" />
        <enterkey-order order="3" control-id="txt_IPRange_Min" />
        <enterkey-order order="4" control-id="txt_IPRange_Max" />
        <enterkey-order order="5" control-id="txt_PasswordLogCheckTime" />
        <enterkey-order order="6" control-id="txt_PasswordMinLength" />
        <enterkey-order order="7" control-id="rdo_FailedLoginUserLock_ON" />
        <enterkey-order order="8" control-id="rdo_FailedLoginAttempts" />
        <enterkey-order order="9" control-id="txt_FailedLoginAttempts" />
        <enterkey-order order="10" control-id="rdo_PwdChangeInterval" />
        <enterkey-order order="11" control-id="txt_PwdChangeInterval" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/Function1" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_MainMenu" />
      </enterkey-orders>
    </page>
    <page path="/emanager/setting/menu/Function2" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ButtonResourceKey" />
        <enterkey-order order="2" control-id="txt_PageNameResouceKey" />
        <enterkey-order order="3" control-id="txt_DsNo" />
        <enterkey-order order="4" control-id="txt_URI" />
        <enterkey-order order="5" control-id="rdo_LoginEnableCheck" />
        <enterkey-order order="6" control-id="rdo_Public" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/listbox/AuthLogList" resource-key="TLE-T0102">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/listbox/MainteLogList" resource-key="TLE-T0104">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/MasterLog" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_TimeRetrievalBeginning" />
        <enterkey-order order="3" control-id="txt_RetrievalEnd" />
        <enterkey-order order="4" control-id="txt_TimeRetrievalEnd" />
        <enterkey-order order="5" control-id="chk_Range" />
        <enterkey-order order="6" control-id="txt_UserId" />
        <enterkey-order order="7" control-id="pul_Master" />
        <enterkey-order order="8" control-id="txt_DsNo" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/InventoryLog" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_TimeRetrievalBeginning" />
        <enterkey-order order="3" control-id="txt_RetrievalEnd" />
        <enterkey-order order="4" control-id="txt_TimeRetrievalEnd" />
        <enterkey-order order="5" control-id="chk_Range" />
        <enterkey-order order="6" control-id="txt_UserId" />
        <enterkey-order order="7" control-id="txt_DsNo" />
        <enterkey-order order="8" control-id="pul_Area" />
        <enterkey-order order="9" control-id="txt_Location" />
        <enterkey-order order="10" control-id="txt_ItemCode" />
        <enterkey-order order="11" control-id="txt_LotNo" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/OperationLog" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_TimeRetrievalBeginning" />
        <enterkey-order order="3" control-id="txt_RetrievalEnd" />
        <enterkey-order order="4" control-id="txt_TimeRetrievalEnd" />
        <enterkey-order order="5" control-id="chk_Range" />
        <enterkey-order order="6" control-id="txt_UserId" />
        <enterkey-order order="7" control-id="txt_DSNo" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/AccessLog" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_RetrievalBeginning" />
        <enterkey-order order="2" control-id="txt_TimeRetrievalBeginning" />
        <enterkey-order order="3" control-id="txt_RetrievalEnd" />
        <enterkey-order order="4" control-id="txt_TimeRetrievalEnd" />
        <enterkey-order order="5" control-id="chk_Range" />
        <enterkey-order order="6" control-id="txt_UserId" />
        <enterkey-order order="7" control-id="txt_DSNo" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logviewimp/AccessLogImp" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/listbox/MasterLogList" resource-key="TLE-T0133">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/listbox/OperationLogList" resource-key="TLE-T0134">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/listbox/AccessLogList" resource-key="TLE-T0146">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/emanager/logview/CsvLogImport" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="lst_LogFileImport" />
      </enterkey-orders>
    </page>
    <page path="/emanager/logview/listbox/DsNoList" resource-key="TLE-T0138">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <!-- eManager END-->
    <page path="/storage/liststart/StorageListStart" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_FromItemCode" />
        <enterkey-order order="3" control-id="txt_ToItemCode" />
        <enterkey-order order="4" control-id="chk_IssueReport" />
        <enterkey-order order="5" control-id="lst_StorageListStart" />
      </enterkey-orders>
    </page>
    <page path="/storage/progress/StorageProgress" resource-key="TLE-W0202">
      <regulartransmission time="30" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="rdo_ProgressDisplayAuto" />
      </enterkey-orders>
    </page>
    <page path="/storage/resultinquiry/StorageResultInquiry" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StorageDateFrom" />
        <enterkey-order order="2" control-id="txt_StorageDateTo" />
        <enterkey-order order="3" control-id="chk_DesignateRange" />
        <enterkey-order order="4" control-id="pul_StorageArea" />
        <enterkey-order order="5" control-id="txt_ItemCode" />
        <enterkey-order order="6" control-id="rdo_PlannedUnit" />
        <enterkey-order order="7" control-id="rdo_DetailDispl" />
      </enterkey-orders>
    </page>
    <page path="/storage/listbox/resultlist/LstStorageResult" resource-key="TLE-W1110">
      <regulartransmission time="0" />
      <enterkey-orders>
      </enterkey-orders>
    </page>
    <page path="/storage/listbox/ticketno/LstStorageTicketNo" resource-key="TLE-W1103">
      <regulartransmission time="0" />
      <enterkey-orders>
      </enterkey-orders>
    </page>
    <page path="/stock/locateworkinginquiry/LocateWorkingInquiry" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="pul_Area" />
        <enterkey-order order="2" control-id="txt_LocationFrom" />
        <enterkey-order order="3" control-id="txt_LocationTo" />
        <enterkey-order order="4" control-id="chk_DesignateRange" />
        <enterkey-order order="5" control-id="txt_ItemCode" />
      </enterkey-orders>
    </page>
    <page path="/stock/listbox/locationworking/LstLocationWorking" resource-key="TLE-W1201">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/stock/listbox/shelf/LstStockShelf" resource-key="TLE-W1212">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/workinquiry/StorageWorkInquiry" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_ItemCode" />
        <enterkey-order order="3" control-id="pul_WorkStatus" />
      </enterkey-orders>
    </page>
    <page path="/storage/listbox/worklist/LstStorageWork" resource-key="TLE-W1108">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/resultmnt/StorageResultMnt" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_ItemCodeFrom" />
        <enterkey-order order="3" control-id="pul_StorageArea" />
        <enterkey-order order="4" control-id="lst_StorageResultMaintenance" />
      </enterkey-orders>
    </page>
    <page path="/storage/planmodify/StoragePlanModify" resource-key="TLE-W0210">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_SlipNumber" />
        <enterkey-order order="3" control-id="txt_LineNo" />
      </enterkey-orders>
    </page>
    <page path="/storage/planmodify/StoragePlanModify2" resource-key="TLE-W0210">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_SlipNumber" />
        <enterkey-order order="3" control-id="txt_LineNo" />
        <enterkey-order order="4" control-id="txt_BranchNo" />
        <enterkey-order order="5" control-id="txt_ItemCode" />
        <enterkey-order order="6" control-id="txt_ItemName" />
        <enterkey-order order="7" control-id="txt_EnteringQty" />
        <enterkey-order order="8" control-id="txt_PlanCaseQty" />
        <enterkey-order order="9" control-id="txt_PlanPieceQty" />
        <enterkey-order order="10" control-id="txt_LotNo" />
        <enterkey-order order="11" control-id="txt_JanCode" />
        <enterkey-order order="12" control-id="txt_CaseITF" />
        <enterkey-order order="13" control-id="pul_StorageArea" />
        <enterkey-order order="14" control-id="txt_StorageLocation" />
      </enterkey-orders>
    </page>
    <page path="/storage/listmnt/StorageListMnt" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_ItemCodeFrom" />
        <enterkey-order order="3" control-id="txt_ItemCodeTo" />
        <enterkey-order order="4" control-id="lst_StorageListMaintenance" />
      </enterkey-orders>
      <dynamicactions />
    </page>
    <page path="/storage/listbox/jobno/LstStorageJobNo" resource-key="TLE-W1106">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/stock/listbox/itemworkingstock/LstItemWorkingStock" resource-key="TLE-W1203">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/item/LstStorageItem" resource-key="TLE-W1104">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/loadunitkey/LstStorageLoadUnitKey" resource-key="TLE-W1107">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/plan/LstStoragePlanMnt" resource-key="TLE-W1111">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/plandate/LstStoragePlanDate" resource-key="TLE-W1112">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/resultdate/LstStorageResultDate" resource-key="TLE-W1102">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/listbox/locate/LstStorageLocate" resource-key="TLE-W1105">
      <regulartransmission time="0" />
      <enterkey-orders />
    </page>
    <page path="/storage/plandelete/StoragePlanDelete" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_SettingUnitKey" />
        <enterkey-order order="3" control-id="chk_IssueReport" />
        <enterkey-order order="4" control-id="lst_StoragePlanDataAllDelete" />
      </enterkey-orders>
    </page>
    <page path="/storage/planregist/StoragePlanRegist" resource-key="TLE-W0209">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_SlipNumber" />
      </enterkey-orders>
    </page>
    <page path="/storage/planregist/StoragePlanRegist2" resource-key="TLE-W0209">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_LineNo" />
        <enterkey-order order="2" control-id="txt_BranchNo" />
        <enterkey-order order="3" control-id="txt_ItemCode" />
        <enterkey-order order="4" control-id="txt_ItemName" />
        <enterkey-order order="5" control-id="txt_EnteringQty" />
        <enterkey-order order="6" control-id="txt_JanCode" />
        <enterkey-order order="7" control-id="txt_CaseITF" />
        <enterkey-order order="8" control-id="txt_PlanCaseQty" />
        <enterkey-order order="9" control-id="txt_PlanPieceQty" />
        <enterkey-order order="10" control-id="txt_LotNo" />
        <enterkey-order order="11" control-id="pul_StorageArea" />
        <enterkey-order order="12" control-id="txt_StorageLocation" />
      </enterkey-orders>
    </page>
    <page path="/system/dataload/DataLoad" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="lst_LoadData" />
      </enterkey-orders>
    </page>
    <page path="/storage/listcomplete/StorageListComplete" resource-key="TLE-W0206">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_StoragePlanDate" />
        <enterkey-order order="2" control-id="txt_ListWorkNo" />
        <enterkey-order order="3" control-id="chk_InitialInputStorageNumber" />
        <enterkey-order order="4" control-id="lst_StorageListResultInput" />
      </enterkey-orders>
    </page>
    <page path="/receiving/progress/ReceivingProgress" resource-key="TLE-W0202">
      <regulartransmission time="30" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="rdo_ProgressDisplayAuto" />
      </enterkey-orders>
    </page>
    <page path="/receiving/resultinquiry/ReceivingResultInquiry" resource-key="">
      <regulartransmission time="0" />
      <enterkey-orders>
        <enterkey-order order="1" control-id="txt_ReceivingDateFrom" />
        <enterkey-order order="2" control-id="txt_ReceivingDateTo" />
        <enterkey-order order="3" control-id="chk_DesignateRange" />